[functions]
  node_bundler = "esbuild"
  included_files = ["/"]
  external_node_modules = ["netlify-express", "express", "sequelize", "express", "pg"]

[build]
  functions="functions"

[[redirects]]
  to="/.netlify/functions/api/:splat"
  from="/*"
  status=200