[functions]
  node_bundler = "esbuild"
  included_files = ["src/*.js", "./src/config/database.js", ".sequelizerc"]
  external_node_modules = ["netlify-express", "express", "sequelize"]

[build]
  functions="functions"

[[redirects]]
  to="/.netlify/functions/api/:splat"
  from="/*"
  status=200